CREATE TABLE IF NOT EXISTS TEACHERS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Full_name TEXT NOT NULL,
  Course_Code TEXT NOT NULL UNIQUE,
  Email TEXT NOT NULL UNIQUE,
  PWD PASSWORD NOT NULL 
);

CREATE TABLE IF NOT EXISTS STUDENTS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Student_name TEXT NOT NULL,
  Student_id TEXT NOT NULL UNIQUE,
  Student_index TEXT NOT NULL UNIQUE,
  PWD PASSWORD NOT NULL
);

CREATE TABLE IF NOT EXISTS GRADES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Student_index TEXT NOT NULL UNIQUE,
  GPA INTEGER ,
  Class TEXT
);

CREATE TABLE IF NOT EXISTS COURSES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE
);
